# Generated by Django 3.2.3 on 2023-10-19 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_alter_journal_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
