# Generated by Django 3.2.3 on 2023-09-24 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_auto_20230815_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студенттер'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('OP', 'Платорфмада'), ('IN', 'Индивидуалды')], default='Платорфмада', max_length=50, verbose_name='Сабақ түрі'),
        ),
    ]
