# Generated by Django 3.2.3 on 2023-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20230924_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='subjectlection',
            options={'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекций'},
        ),
        migrations.AlterModelOptions(
            name='taskisfill',
            options={'verbose_name': 'Задание ', 'verbose_name_plural': 'Задание (Заполнит)'},
        ),
        migrations.AlterModelOptions(
            name='taskisidentify',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задание (Сопоставить)'},
        ),
        migrations.AlterModelOptions(
            name='taskistest',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задание (Тест)'},
        ),
        migrations.AlterModelOptions(
            name='userresult',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('OP', 'В платформе'), ('IN', 'Индивидуальный')], default='В платформе', max_length=50, verbose_name='Сабақ түрі'),
        ),
        migrations.AlterField(
            model_name='taskisfill',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskisfill',
            name='body',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskisfill',
            name='t_type',
            field=models.CharField(choices=[('Заполнит пустую линию', 'Заполнит пустую линию'), ('Завершит код', 'Завершит код')], default='Заполнит пустую линию', max_length=100, verbose_name='Тип заданий'),
        ),
        migrations.AlterField(
            model_name='taskisfill',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок задание'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='answer_1',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='answer_2',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='answer_3',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='answer_4',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='body',
            field=models.TextField(verbose_name='Текст заданий'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='task_1',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='task_2',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='task_3',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='task_4',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskisidentify',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок заданий '),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='answer_1',
            field=models.CharField(max_length=200, verbose_name='Вариант (1)'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='answer_2',
            field=models.CharField(max_length=200, verbose_name='Вариант (2)'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='answer_3',
            field=models.CharField(max_length=200, verbose_name='Вариант (3)'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='answer_4',
            field=models.CharField(default='Нұсқа (4)', max_length=200, verbose_name='Вариант (4)'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='answer_true',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='body',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='taskistest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок задание'),
        ),
    ]
