# Generated by Django 3.2.3 on 2023-10-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20231012_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('OP', 'В платформе'), ('IN', 'Индивидуальный')], default='В платформе', max_length=50, verbose_name='Сабақ түрі'),
        ),
    ]
